-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.128.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 31/08/2015 09:27:43 a. m.
-- Server version: 5.5.30
-- Client version: 4.1

--
-- Definition for database gm_negocio
--
DROP DATABASE IF EXISTS gm_negocio;
CREATE DATABASE gm_negocio
	CHARACTER SET utf8
	COLLATE utf8_general_ci;

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE gm_negocio;

--
-- Definition for table alm_categorias
--
CREATE TABLE alm_categorias (
  id_categoria INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(150) DEFAULT NULL,
  descripcion VARCHAR(250) DEFAULT NULL,
  PRIMARY KEY (id_categoria)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table alm_movimientos
--
CREATE TABLE alm_movimientos (
  id_movimiento BIGINT(20) NOT NULL AUTO_INCREMENT,
  tipo INT(1) DEFAULT NULL COMMENT '1) Entrada, 2) Salida',
  descripcion VARCHAR(255) DEFAULT NULL COMMENT 'Breve descripcion del movimiento',
  responsable VARCHAR(255) DEFAULT NULL COMMENT 'Nombre del responsable',
  fecha DATETIME DEFAULT NULL,
  PRIMARY KEY (id_movimiento)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table alm_proveedores
--
CREATE TABLE alm_proveedores (
  id_proveedor INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(150) DEFAULT NULL,
  encargado VARCHAR(150) DEFAULT NULL,
  razon_social VARCHAR(150) DEFAULT NULL,
  rfc VARCHAR(18) DEFAULT NULL,
  calle VARCHAR(254) DEFAULT NULL,
  n_ext VARCHAR(6) DEFAULT NULL,
  n_int VARCHAR(6) DEFAULT NULL,
  colonia VARCHAR(50) DEFAULT NULL,
  cp VARCHAR(10) DEFAULT NULL,
  localidad VARCHAR(254) DEFAULT NULL,
  municipio VARCHAR(254) DEFAULT NULL,
  estado VARCHAR(100) DEFAULT NULL,
  telefono VARCHAR(100) DEFAULT NULL,
  email VARCHAR(150) DEFAULT NULL,
  PRIMARY KEY (id_proveedor)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table cfg_bitacora
--
CREATE TABLE cfg_bitacora (
  id_bitacora BIGINT(11) NOT NULL AUTO_INCREMENT,
  movimiento VARCHAR(255) DEFAULT NULL,
  id_usuario INT(11) DEFAULT NULL,
  fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id_bitacora)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table cfg_configuracion
--
CREATE TABLE cfg_configuracion (
  id_cfg INT(11) NOT NULL AUTO_INCREMENT,
  regimen VARCHAR(254) DEFAULT '',
  nombre VARCHAR(150) DEFAULT '',
  rfc VARCHAR(18) DEFAULT NULL,
  calle VARCHAR(254) DEFAULT '',
  n_ext VARCHAR(6) DEFAULT '',
  n_int VARCHAR(6) DEFAULT '',
  colonia VARCHAR(50) DEFAULT '',
  cp VARCHAR(10) DEFAULT '',
  localidad VARCHAR(254) DEFAULT '',
  municipio VARCHAR(254) DEFAULT '',
  estado VARCHAR(100) DEFAULT '',
  telefono VARCHAR(100) DEFAULT '',
  email VARCHAR(150) DEFAULT '',
  iva DECIMAL(4, 2) DEFAULT 0.00,
  ieps DECIMAL(4, 2) DEFAULT 0.00,
  ret_iva DECIMAL(4, 2) DEFAULT 0.00,
  ret_isr DECIMAL(4, 2) DEFAULT 0.00,
  lugar_expedicion VARCHAR(255) DEFAULT '',
  serie VARCHAR(3) DEFAULT '',
  folio_actual INT(5) DEFAULT 0,
  folio_final INT(5) DEFAULT 0,
  foto_perfil INT(1) DEFAULT 1 COMMENT 'Tipo de logo 1) Cuadrado, 2)Banner',
  path_cer VARCHAR(255) DEFAULT '',
  path_key VARCHAR(255) DEFAULT '',
  sello_pass VARCHAR(255) DEFAULT '',
  cadena_cer LONGTEXT DEFAULT NULL,
  num_cer VARCHAR(255) DEFAULT '',
  logo_cuadrado VARCHAR(255) DEFAULT '',
  logo_banner VARCHAR(255) DEFAULT '',
  PRIMARY KEY (id_cfg)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table cfg_usuarios
--
CREATE TABLE cfg_usuarios (
  id_usuario INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(100) DEFAULT NULL,
  apellido VARCHAR(150) DEFAULT NULL,
  tipo INT(1) DEFAULT NULL COMMENT '1)Administrador, 2)Usuario, 3) Vendedor',
  usuario VARCHAR(10) DEFAULT NULL,
  password VARCHAR(8) DEFAULT NULL,
  PRIMARY KEY (id_usuario),
  UNIQUE INDEX usuario (usuario)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table clientes
--
CREATE TABLE clientes (
  id_cliente INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(150) DEFAULT NULL,
  encargado VARCHAR(150) DEFAULT NULL,
  razon_social VARCHAR(150) DEFAULT NULL,
  rfc VARCHAR(18) DEFAULT NULL,
  calle VARCHAR(254) DEFAULT NULL,
  n_ext VARCHAR(6) DEFAULT NULL,
  n_int VARCHAR(6) DEFAULT NULL,
  colonia VARCHAR(50) DEFAULT NULL,
  cp VARCHAR(10) DEFAULT NULL,
  localidad VARCHAR(254) DEFAULT NULL,
  municipio VARCHAR(254) DEFAULT NULL,
  estado VARCHAR(100) DEFAULT NULL,
  telefono VARCHAR(100) DEFAULT NULL,
  email VARCHAR(150) DEFAULT NULL,
  PRIMARY KEY (id_cliente)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table cont_categorias
--
CREATE TABLE cont_categorias (
  id_categoria INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(100) DEFAULT NULL,
  color VARCHAR(15) DEFAULT NULL,
  descripcion VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id_categoria)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table cont_cuentas
--
CREATE TABLE cont_cuentas (
  id_cuenta INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(255) DEFAULT NULL,
  descripcion VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id_cuenta)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table cont_movimientos
--
CREATE TABLE cont_movimientos (
  id_movimiento BIGINT(20) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(100) DEFAULT NULL,
  concepto VARCHAR(255) DEFAULT NULL,
  monto DECIMAL(10, 5) DEFAULT NULL,
  id_categoria INT(11) DEFAULT NULL,
  id_cuenta INT(11) DEFAULT NULL,
  fecha DATETIME DEFAULT NULL,
  adjunto VARCHAR(255) DEFAULT NULL,
  metodo_pago VARCHAR(255) DEFAULT NULL,
  tipo INT(11) DEFAULT NULL COMMENT '1) Ingreso, 2) Gasto, 3)Transeferencia',
  PRIMARY KEY (id_movimiento)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table alm_productos
--
CREATE TABLE alm_productos (
  id_producto BIGINT(20) NOT NULL AUTO_INCREMENT,
  identificador VARCHAR(100) DEFAULT NULL,
  nombre VARCHAR(254) DEFAULT NULL,
  descripcion VARCHAR(254) DEFAULT NULL,
  unidad_medida VARCHAR(100) DEFAULT NULL,
  n_parte VARCHAR(15) DEFAULT NULL,
  tipo INT(1) DEFAULT NULL COMMENT '1) Producto fisico, 2)Servicio',
  id_categoria INT(11) DEFAULT NULL,
  id_provedor INT(11) DEFAULT NULL,
  precio_compra DECIMAL(10, 5) DEFAULT NULL,
  precio_venta DECIMAL(10, 5) DEFAULT NULL,
  inventario_alto DECIMAL(10, 5) DEFAULT NULL,
  inventario_bajo DECIMAL(10, 5) DEFAULT NULL,
  PRIMARY KEY (id_producto),
  INDEX id_provedor (id_provedor),
  CONSTRAINT alm_productos_ibfk_1 FOREIGN KEY (id_provedor)
    REFERENCES alm_proveedores(id_proveedor) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_categoria FOREIGN KEY (id_categoria)
    REFERENCES alm_categorias(id_categoria) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table compras
--
CREATE TABLE compras (
  id_compra BIGINT(20) NOT NULL AUTO_INCREMENT,
  folio VARCHAR(30) DEFAULT NULL,
  uuidfactura VARCHAR(50) DEFAULT NULL,
  subtotal DECIMAL(10, 5) DEFAULT NULL,
  total DECIMAL(10, 5) DEFAULT NULL,
  iva_tras DECIMAL(10, 5) DEFAULT NULL,
  iva_ret DECIMAL(10, 5) DEFAULT NULL,
  isr_tras DECIMAL(10, 5) DEFAULT NULL,
  isr_ret DECIMAL(10, 5) DEFAULT NULL,
  xml VARCHAR(10) DEFAULT NULL,
  fecha DATETIME DEFAULT NULL,
  id_proveedor INT(11) DEFAULT NULL,
  PRIMARY KEY (id_compra),
  INDEX id_proveedor (id_proveedor),
  CONSTRAINT compras_ibfk_1 FOREIGN KEY (id_proveedor)
    REFERENCES alm_proveedores(id_proveedor) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table cotizaciones
--
CREATE TABLE cotizaciones (
  id_cotizacion BIGINT(20) NOT NULL AUTO_INCREMENT,
  folio VARCHAR(100) DEFAULT NULL,
  id_cliente INT(11) DEFAULT NULL,
  fecha DATETIME DEFAULT NULL,
  condicion_pago VARCHAR(150) DEFAULT NULL,
  plazo_entrega VARCHAR(150) DEFAULT NULL,
  cond_embarque VARCHAR(250) DEFAULT NULL,
  atn VARCHAR(150) DEFAULT NULL,
  subtotal DECIMAL(10, 5) DEFAULT 0.00000,
  iva DECIMAL(10, 5) DEFAULT 0.00000,
  total DECIMAL(10, 5) DEFAULT 0.00000,
  status INT(1) DEFAULT 1 COMMENT 'Estatus de la cotización. 1) Enviada, 2) Aceptada, 3) Rechazada, 4)Pedido, 5)Venta Realizada',
  PRIMARY KEY (id_cotizacion),
  INDEX id_cliente (id_cliente),
  CONSTRAINT cotizaciones_ibfk_1 FOREIGN KEY (id_cliente)
    REFERENCES clientes(id_cliente) ON DELETE NO ACTION ON UPDATE NO ACTION
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table ventas
--
CREATE TABLE ventas (
  id_venta BIGINT(20) NOT NULL AUTO_INCREMENT,
  id_cliente INT(11) DEFAULT NULL,
  codigo VARCHAR(255) DEFAULT NULL,
  fecha DATETIME DEFAULT NULL,
  importe_sub DECIMAL(10, 5) DEFAULT NULL,
  iva_tras DECIMAL(10, 5) DEFAULT NULL,
  iva_ret DECIMAL(10, 5) DEFAULT NULL,
  isr_tras DECIMAL(10, 5) DEFAULT NULL,
  isr_ret DECIMAL(10, 5) DEFAULT NULL,
  total DECIMAL(10, 5) DEFAULT NULL,
  metodo_pago VARCHAR(255) DEFAULT NULL,
  id_cotizacion BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (id_venta),
  INDEX id_cliente (id_cliente),
  CONSTRAINT ventas_ibfk_1 FOREIGN KEY (id_cliente)
    REFERENCES clientes(id_cliente) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table alm_movimiento_detalles
--
CREATE TABLE alm_movimiento_detalles (
  id_detalle BIGINT(20) NOT NULL AUTO_INCREMENT,
  id_movimiento BIGINT(20) DEFAULT NULL,
  id_producto BIGINT(20) DEFAULT NULL,
  cantidad DECIMAL(10, 5) DEFAULT NULL,
  PRIMARY KEY (id_detalle),
  CONSTRAINT fk_padre FOREIGN KEY (id_movimiento)
    REFERENCES alm_movimientos(id_movimiento) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_producto FOREIGN KEY (id_producto)
    REFERENCES alm_productos(id_producto) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table compras_detalle
--
CREATE TABLE compras_detalle (
  id_detalle BIGINT(20) NOT NULL AUTO_INCREMENT,
  id_compra BIGINT(20) DEFAULT NULL,
  cantidad DECIMAL(10, 5) DEFAULT NULL,
  descripcion VARCHAR(255) DEFAULT NULL,
  importe DECIMAL(10, 5) DEFAULT NULL,
  noIdentificacion VARCHAR(255) DEFAULT NULL,
  unidad VARCHAR(255) DEFAULT NULL,
  valorUnitario DECIMAL(10, 5) DEFAULT NULL,
  PRIMARY KEY (id_detalle),
  INDEX id_compra (id_compra),
  CONSTRAINT compras_detalle_ibfk_1 FOREIGN KEY (id_compra)
    REFERENCES compras(id_compra) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table cotizaciones_detalle
--
CREATE TABLE cotizaciones_detalle (
  id_detalle BIGINT(20) NOT NULL AUTO_INCREMENT,
  id_cotizacion BIGINT(20) DEFAULT NULL,
  id_producto BIGINT(20) DEFAULT NULL,
  cantidad VARCHAR(255) DEFAULT NULL,
  unidad VARCHAR(255) DEFAULT NULL,
  precio VARCHAR(255) DEFAULT NULL,
  total VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id_detalle),
  INDEX id_cotizacion (id_cotizacion),
  INDEX id_producto (id_producto),
  CONSTRAINT cotizaciones_detalle_ibfk_2 FOREIGN KEY (id_producto)
    REFERENCES alm_productos(id_producto) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT cotizaciones_detalle_ibfk_3 FOREIGN KEY (id_cotizacion)
    REFERENCES cotizaciones(id_cotizacion) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table ventas_detalle
--
CREATE TABLE ventas_detalle (
  id_detalle BIGINT(20) NOT NULL AUTO_INCREMENT,
  id_venta BIGINT(20) DEFAULT NULL,
  id_producto BIGINT(20) DEFAULT NULL,
  cantidad DECIMAL(10, 5) DEFAULT NULL,
  precio DECIMAL(10, 5) DEFAULT NULL,
  importe_iva DECIMAL(10, 5) DEFAULT NULL,
  importe_ieps DECIMAL(10, 5) DEFAULT NULL,
  unidad VARCHAR(100) DEFAULT NULL,
  total DECIMAL(10, 5) DEFAULT NULL,
  PRIMARY KEY (id_detalle),
  INDEX id_producto (id_producto),
  INDEX id_venta (id_venta),
  CONSTRAINT ventas_detalle_ibfk_1 FOREIGN KEY (id_venta)
    REFERENCES ventas(id_venta) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT ventas_detalle_ibfk_2 FOREIGN KEY (id_producto)
    REFERENCES alm_productos(id_producto) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

-- 
-- Dumping data for table alm_categorias
--

-- Table gm_negocio.alm_categorias does not contain any data (it is empty)

-- 
-- Dumping data for table alm_movimientos
--

-- Table gm_negocio.alm_movimientos does not contain any data (it is empty)

-- 
-- Dumping data for table alm_proveedores
--
INSERT INTO alm_proveedores VALUES
(1, 'ANGEL GUTIERREZ MONOLA', NULL, NULL, 'GUMA91269K3', 'BOULEVARD MANUEL AVILA CAMACHO', '114', '', 'CENTRO', '96400', 'COATZALCOALCOS', 'COATZACOALCOS', 'VERACRUZ', '921232', 'gutierrez.monola@gmail.com');

-- 
-- Dumping data for table cfg_bitacora
--

-- Table gm_negocio.cfg_bitacora does not contain any data (it is empty)

-- 
-- Dumping data for table cfg_configuracion
--
INSERT INTO cfg_configuracion VALUES
(1, 'x', 'xx', 'xxx', 'xx', 'x', 'xx', 'xx', 'xxx', 'xx', 'xx', 'xx', 'x', 'x', 0.00, 0.00, 0.00, 0.00, 'MODIFICAR', 'X', 1, 0, 1, '', '', '', 'xxx', '', '', '');

-- 
-- Dumping data for table cfg_usuarios
--

-- Table gm_negocio.cfg_usuarios does not contain any data (it is empty)

-- 
-- Dumping data for table clientes
--
INSERT INTO clientes VALUES
(1, 'ANGEL GUTIERREZ MONOLA', NULL, NULL, 'GUMA91269K3', 'BOULEVARD MANUEL AVILA CAMACHO', '114', '', 'CENTRO', '96400', 'COATZALCOALCOS', 'COATZACOALCOS', 'VERACRUZ', '921232', 'gutierrez.monola@gmail.com');

-- 
-- Dumping data for table cont_categorias
--

-- Table gm_negocio.cont_categorias does not contain any data (it is empty)

-- 
-- Dumping data for table cont_cuentas
--

-- Table gm_negocio.cont_cuentas does not contain any data (it is empty)

-- 
-- Dumping data for table cont_movimientos
--

-- Table gm_negocio.cont_movimientos does not contain any data (it is empty)

-- 
-- Dumping data for table alm_productos
--

-- Table gm_negocio.alm_productos does not contain any data (it is empty)

-- 
-- Dumping data for table compras
--

-- Table gm_negocio.compras does not contain any data (it is empty)

-- 
-- Dumping data for table cotizaciones
--

-- Table gm_negocio.cotizaciones does not contain any data (it is empty)

-- 
-- Dumping data for table ventas
--

-- Table gm_negocio.ventas does not contain any data (it is empty)

-- 
-- Dumping data for table alm_movimiento_detalles
--

-- Table gm_negocio.alm_movimiento_detalles does not contain any data (it is empty)

-- 
-- Dumping data for table compras_detalle
--

-- Table gm_negocio.compras_detalle does not contain any data (it is empty)

-- 
-- Dumping data for table cotizaciones_detalle
--

-- Table gm_negocio.cotizaciones_detalle does not contain any data (it is empty)

-- 
-- Dumping data for table ventas_detalle
--

-- Table gm_negocio.ventas_detalle does not contain any data (it is empty)

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;