-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.128.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 08/12/2015 04:42:55 p.m.
-- Server version: 5.6.26-log
-- Client version: 4.1

--
-- Definition for database gm_negocio
--
DROP DATABASE IF EXISTS gm_negocio;
CREATE DATABASE gm_negocio
	CHARACTER SET utf8
	COLLATE utf8_general_ci;

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE gm_negocio;

--
-- Definition for table alm_categorias
--
CREATE TABLE alm_categorias (
  id_categoria INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(150) DEFAULT NULL,
  descripcion VARCHAR(250) DEFAULT NULL,
  PRIMARY KEY (id_categoria)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table alm_movimientos
--
CREATE TABLE alm_movimientos (
  id_movimiento BIGINT(20) NOT NULL AUTO_INCREMENT,
  tipo INT(1) DEFAULT NULL COMMENT '1) Entrada, 2) Salida',
  descripcion VARCHAR(255) DEFAULT NULL COMMENT 'Breve descripcion del movimiento',
  responsable VARCHAR(255) DEFAULT NULL COMMENT 'Nombre del responsable',
  fecha DATETIME DEFAULT NULL,
  PRIMARY KEY (id_movimiento)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table alm_proveedores
--
CREATE TABLE alm_proveedores (
  id_proveedor INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(150) DEFAULT NULL,
  encargado VARCHAR(150) DEFAULT NULL,
  razon_social VARCHAR(150) DEFAULT NULL,
  rfc VARCHAR(18) DEFAULT NULL,
  calle VARCHAR(254) DEFAULT NULL,
  n_ext VARCHAR(6) DEFAULT NULL,
  n_int VARCHAR(6) DEFAULT NULL,
  colonia VARCHAR(50) DEFAULT NULL,
  cp VARCHAR(10) DEFAULT NULL,
  localidad VARCHAR(254) DEFAULT NULL,
  municipio VARCHAR(254) DEFAULT NULL,
  estado VARCHAR(100) DEFAULT NULL,
  telefono VARCHAR(100) DEFAULT NULL,
  email VARCHAR(150) DEFAULT NULL,
  PRIMARY KEY (id_proveedor)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table cfg_bitacora
--
CREATE TABLE cfg_bitacora (
  id_bitacora BIGINT(11) NOT NULL AUTO_INCREMENT,
  movimiento VARCHAR(255) DEFAULT NULL,
  id_usuario INT(11) DEFAULT NULL,
  fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id_bitacora)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table cfg_configuracion
--
CREATE TABLE cfg_configuracion (
  id_cfg INT(11) NOT NULL AUTO_INCREMENT,
  regimen VARCHAR(254) DEFAULT '',
  nombre VARCHAR(150) DEFAULT '',
  rfc VARCHAR(18) DEFAULT NULL,
  calle VARCHAR(254) DEFAULT '',
  n_ext VARCHAR(6) DEFAULT '',
  n_int VARCHAR(6) DEFAULT '',
  colonia VARCHAR(50) DEFAULT '',
  cp VARCHAR(10) DEFAULT '',
  localidad VARCHAR(254) DEFAULT '',
  municipio VARCHAR(254) DEFAULT '',
  estado VARCHAR(100) DEFAULT '',
  telefono VARCHAR(100) DEFAULT '',
  email VARCHAR(150) DEFAULT '',
  iva DECIMAL(4, 2) DEFAULT 0.00,
  ieps DECIMAL(4, 2) DEFAULT 0.00,
  ret_iva DECIMAL(4, 2) DEFAULT 0.00,
  ret_isr DECIMAL(4, 2) DEFAULT 0.00,
  lugar_expedicion VARCHAR(255) DEFAULT '',
  serie VARCHAR(3) DEFAULT '',
  folio_actual INT(5) DEFAULT 0,
  folio_final INT(5) DEFAULT 0,
  foto_perfil INT(1) DEFAULT 1 COMMENT 'Tipo de logo 1) Cuadrado, 2)Banner',
  path_cer VARCHAR(255) DEFAULT '',
  path_key VARCHAR(255) DEFAULT '',
  sello_pass VARCHAR(255) DEFAULT '',
  cadena_cer LONGTEXT DEFAULT NULL,
  num_cer VARCHAR(255) DEFAULT '',
  logo_cuadrado VARCHAR(255) DEFAULT '',
  logo_banner VARCHAR(255) DEFAULT '',
  cot_folio INT(11) DEFAULT NULL,
  cot_serie VARCHAR(3) DEFAULT NULL,
  ventas_folio INT(11) DEFAULT NULL,
  ventas_serie VARCHAR(3) DEFAULT NULL,
  PRIMARY KEY (id_cfg)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table cfg_usuarios
--
CREATE TABLE cfg_usuarios (
  id_usuario INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(100) DEFAULT NULL,
  apellido VARCHAR(150) DEFAULT NULL,
  tipo INT(1) DEFAULT NULL COMMENT '1)Administrador, 2)Usuario, 3) Vendedor',
  usuario VARCHAR(10) DEFAULT NULL,
  password VARCHAR(8) DEFAULT NULL,
  PRIMARY KEY (id_usuario),
  UNIQUE INDEX usuario (usuario)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table clientes
--
CREATE TABLE clientes (
  id_cliente INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(150) DEFAULT NULL,
  encargado VARCHAR(150) DEFAULT NULL,
  razon_social VARCHAR(150) DEFAULT NULL,
  rfc VARCHAR(18) DEFAULT NULL,
  calle VARCHAR(254) DEFAULT NULL,
  n_ext VARCHAR(6) DEFAULT NULL,
  n_int VARCHAR(6) DEFAULT NULL,
  colonia VARCHAR(50) DEFAULT NULL,
  cp VARCHAR(10) DEFAULT NULL,
  localidad VARCHAR(254) DEFAULT NULL,
  municipio VARCHAR(254) DEFAULT NULL,
  estado VARCHAR(100) DEFAULT NULL,
  telefono VARCHAR(100) DEFAULT NULL,
  email VARCHAR(150) DEFAULT NULL,
  PRIMARY KEY (id_cliente)
)
ENGINE = INNODB
AUTO_INCREMENT = 4
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table cont_categorias
--
CREATE TABLE cont_categorias (
  id_categoria INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(100) DEFAULT NULL,
  color VARCHAR(15) DEFAULT NULL,
  descripcion VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id_categoria)
)
ENGINE = INNODB
AUTO_INCREMENT = 7
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table cont_cuentas
--
CREATE TABLE cont_cuentas (
  id_cuenta INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(255) DEFAULT NULL,
  descripcion VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id_cuenta)
)
ENGINE = INNODB
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table alm_productos
--
CREATE TABLE alm_productos (
  id_producto BIGINT(20) NOT NULL AUTO_INCREMENT,
  identificador VARCHAR(100) DEFAULT NULL,
  nombre VARCHAR(254) DEFAULT NULL,
  descripcion VARCHAR(254) DEFAULT NULL,
  unidad_medida VARCHAR(100) DEFAULT NULL,
  n_parte VARCHAR(15) DEFAULT NULL,
  tipo INT(1) DEFAULT NULL COMMENT '1) Producto fisico, 2)Servicio',
  id_categoria INT(11) DEFAULT NULL,
  id_provedor INT(11) DEFAULT NULL,
  precio_compra DECIMAL(10, 5) DEFAULT NULL,
  precio_venta DECIMAL(10, 5) DEFAULT NULL,
  inventario_alto DECIMAL(10, 5) DEFAULT NULL,
  inventario_bajo DECIMAL(10, 5) DEFAULT NULL,
  iva DECIMAL(10, 5) DEFAULT NULL,
  ieps DECIMAL(10, 5) DEFAULT NULL,
  PRIMARY KEY (id_producto),
  INDEX id_provedor (id_provedor),
  CONSTRAINT alm_productos_ibfk_1 FOREIGN KEY (id_provedor)
    REFERENCES alm_proveedores(id_proveedor) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_categoria FOREIGN KEY (id_categoria)
    REFERENCES alm_categorias(id_categoria) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table compras
--
CREATE TABLE compras (
  id_compra BIGINT(20) NOT NULL AUTO_INCREMENT,
  folio VARCHAR(30) DEFAULT NULL,
  uuidfactura VARCHAR(50) DEFAULT NULL,
  subtotal DECIMAL(10, 5) DEFAULT NULL,
  total DECIMAL(10, 5) DEFAULT NULL,
  iva_tras DECIMAL(10, 5) DEFAULT NULL,
  iva_ret DECIMAL(10, 5) DEFAULT NULL,
  isr_tras DECIMAL(10, 5) DEFAULT NULL,
  isr_ret DECIMAL(10, 5) DEFAULT NULL,
  xml VARCHAR(10) DEFAULT NULL,
  fecha DATETIME DEFAULT NULL,
  id_proveedor INT(11) DEFAULT NULL,
  PRIMARY KEY (id_compra),
  INDEX id_proveedor (id_proveedor),
  CONSTRAINT compras_ibfk_1 FOREIGN KEY (id_proveedor)
    REFERENCES alm_proveedores(id_proveedor) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table cont_movimientos
--
CREATE TABLE cont_movimientos (
  id_movimiento BIGINT(20) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(100) DEFAULT NULL,
  concepto VARCHAR(255) DEFAULT NULL,
  monto DECIMAL(10, 5) DEFAULT NULL,
  id_categoria INT(11) DEFAULT NULL,
  id_cuenta INT(11) DEFAULT NULL,
  fecha DATETIME DEFAULT NULL,
  adjunto VARCHAR(255) DEFAULT NULL,
  metodo_pago VARCHAR(255) DEFAULT NULL,
  tipo INT(11) DEFAULT NULL COMMENT '1) Ingreso, 2) Gasto, 3)Transeferencia',
  id_usuario INT(11) DEFAULT NULL,
  PRIMARY KEY (id_movimiento),
  CONSTRAINT FK_cont_movimientos_cfg_usuarios_id_usuario FOREIGN KEY (id_usuario)
    REFERENCES cfg_usuarios(id_usuario) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_cont_movimientos_cont_categorias_id_categoria FOREIGN KEY (id_categoria)
    REFERENCES cont_categorias(id_categoria) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_cont_movimientos_cont_cuentas_id_cuenta FOREIGN KEY (id_cuenta)
    REFERENCES cont_cuentas(id_cuenta) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table ventas
--
CREATE TABLE ventas (
  id_venta BIGINT(20) NOT NULL AUTO_INCREMENT,
  id_cliente INT(11) DEFAULT NULL,
  folio_venta VARCHAR(255) DEFAULT NULL,
  folio_cotizacion VARCHAR(100) DEFAULT NULL,
  fecha_cotizacion DATETIME DEFAULT NULL,
  fecha DATETIME DEFAULT NULL,
  importe_sub DECIMAL(10, 5) DEFAULT 0.00000,
  iva_tras DECIMAL(10, 5) NOT NULL DEFAULT 0.00000,
  iva_ret DECIMAL(10, 5) NOT NULL DEFAULT 0.00000,
  isr_tras DECIMAL(10, 5) NOT NULL DEFAULT 0.00000,
  ieps DECIMAL(10, 5) NOT NULL DEFAULT 0.00000,
  isr_ret DECIMAL(10, 5) NOT NULL DEFAULT 0.00000,
  total DECIMAL(10, 5) NOT NULL DEFAULT 0.00000,
  metodo_pago VARCHAR(255) NOT NULL DEFAULT '0',
  status INT(1) NOT NULL DEFAULT 1 COMMENT '1)Pendiente, 2)Cancelada, 3)Finalizada',
  forma_pago VARCHAR(255) DEFAULT NULL,
  condicion_pago VARCHAR(255) DEFAULT NULL,
  condicion_embarque VARCHAR(255) DEFAULT NULL,
  plazo_entrega VARCHAR(255) DEFAULT NULL,
  tipo INT(1) DEFAULT NULL COMMENT '1)Cotización, 2)Venta, 3)Cotización de Venta',
  num_cta VARCHAR(255) DEFAULT NULL,
  importe_desc VARCHAR(255) DEFAULT NULL,
  facturado INT(11) NOT NULL DEFAULT 0 COMMENT '0) No, 1) Si',
  PRIMARY KEY (id_venta),
  INDEX id_cliente (id_cliente),
  CONSTRAINT ventas_ibfk_1 FOREIGN KEY (id_cliente)
    REFERENCES clientes(id_cliente) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 4
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table alm_movimiento_detalles
--
CREATE TABLE alm_movimiento_detalles (
  id_detalle BIGINT(20) NOT NULL AUTO_INCREMENT,
  id_movimiento BIGINT(20) DEFAULT NULL,
  id_producto BIGINT(20) DEFAULT NULL,
  cantidad DECIMAL(10, 5) DEFAULT NULL,
  PRIMARY KEY (id_detalle),
  CONSTRAINT fk_padre FOREIGN KEY (id_movimiento)
    REFERENCES alm_movimientos(id_movimiento) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_producto FOREIGN KEY (id_producto)
    REFERENCES alm_productos(id_producto) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table compras_detalle
--
CREATE TABLE compras_detalle (
  id_detalle BIGINT(20) NOT NULL AUTO_INCREMENT,
  id_compra BIGINT(20) DEFAULT NULL,
  cantidad DECIMAL(10, 5) DEFAULT NULL,
  descripcion VARCHAR(255) DEFAULT NULL,
  importe DECIMAL(10, 5) DEFAULT NULL,
  noIdentificacion VARCHAR(255) DEFAULT NULL,
  unidad VARCHAR(255) DEFAULT NULL,
  valorUnitario DECIMAL(10, 5) DEFAULT NULL,
  PRIMARY KEY (id_detalle),
  INDEX id_compra (id_compra),
  CONSTRAINT compras_detalle_ibfk_1 FOREIGN KEY (id_compra)
    REFERENCES compras(id_compra) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table ventas_detalle
--
CREATE TABLE ventas_detalle (
  id_detalle BIGINT(20) NOT NULL AUTO_INCREMENT,
  id_venta BIGINT(20) DEFAULT NULL,
  id_producto BIGINT(20) DEFAULT NULL,
  cantidad DECIMAL(10, 5) DEFAULT NULL,
  precio DECIMAL(10, 5) DEFAULT NULL,
  importe_iva DECIMAL(10, 5) DEFAULT NULL,
  importe_ieps DECIMAL(10, 5) DEFAULT NULL,
  unidad VARCHAR(100) DEFAULT NULL,
  descuento DECIMAL(10, 5) NOT NULL DEFAULT 0.00000,
  total DECIMAL(10, 5) DEFAULT NULL,
  PRIMARY KEY (id_detalle),
  INDEX id_producto (id_producto),
  INDEX id_venta (id_venta),
  CONSTRAINT ventas_detalle_ibfk_1 FOREIGN KEY (id_venta)
    REFERENCES ventas(id_venta) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT ventas_detalle_ibfk_2 FOREIGN KEY (id_producto)
    REFERENCES alm_productos(id_producto) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for view v_clientes
--
CREATE OR REPLACE 
VIEW v_clientes
AS
	select `c`.`id_cliente` AS `id_cliente`,`c`.`nombre` AS `nombre`,`c`.`encargado` AS `encargado`,`c`.`razon_social` AS `razon_social`,`c`.`rfc` AS `rfc`,`c`.`calle` AS `calle`,`c`.`n_ext` AS `n_ext`,`c`.`n_int` AS `n_int`,`c`.`colonia` AS `colonia`,`c`.`cp` AS `cp`,`c`.`localidad` AS `localidad`,`c`.`municipio` AS `municipio`,`c`.`telefono` AS `telefono`,`c`.`estado` AS `estado`,`c`.`email` AS `email`,concat_ws(' ',`c`.`nombre`,`c`.`encargado`,`c`.`razon_social`,`c`.`rfc`,`c`.`calle`,`c`.`n_ext`,`c`.`n_int`,`c`.`colonia`,`c`.`cp`,`c`.`localidad`,`c`.`municipio`,`c`.`telefono`,`c`.`estado`,`c`.`email`) AS `campo_buscar` from `clientes` `c`;

--
-- Definition for view v_cont_movimientos
--
CREATE OR REPLACE 
VIEW v_cont_movimientos
AS
	select `cm`.`id_movimiento` AS `id_movimiento`,`cm`.`nombre` AS `nombre`,`cm`.`monto` AS `monto`,`cm`.`concepto` AS `concepto`,`cm`.`id_categoria` AS `id_categoria`,`cc`.`nombre` AS `categoria`,`cm`.`id_cuenta` AS `id_cuenta`,`cu`.`nombre` AS `cuenta`,`cm`.`fecha` AS `fecha`,`cm`.`adjunto` AS `adjunto`,`cm`.`metodo_pago` AS `metodo_pago`,`cm`.`tipo` AS `tipo`,`cm`.`id_usuario` AS `id_usuario`,`u`.`nombre` AS `usuario`,concat_ws(' ',`cm`.`nombre`,`cm`.`concepto`,`cc`.`nombre`,`cu`.`nombre`,`cm`.`metodo_pago`,`cm`.`tipo`,`u`.`nombre`) AS `campo_buscar` from (((`cont_movimientos` `cm` join `cont_categorias` `cc`) join `cont_cuentas` `cu`) join `cfg_usuarios` `u`) where ((`cc`.`id_categoria` = `cm`.`id_categoria`) and (`cu`.`id_cuenta` = `cm`.`id_cuenta`) and (`u`.`id_usuario` = `cm`.`id_usuario`));

--
-- Definition for view v_cotizaciones
--
CREATE OR REPLACE 
VIEW v_cotizaciones
AS
	select `v`.`id_venta` AS `id_cotizacion`,`v`.`id_cliente` AS `id_cliente`,`v`.`folio_cotizacion` AS `folio`,`v`.`fecha_cotizacion` AS `fecha`,`v`.`importe_sub` AS `subtotal`,`v`.`iva_tras` AS `iva`,`v`.`ieps` AS `ieps`,`v`.`total` AS `total`,`v`.`metodo_pago` AS `metodo_pago`,`v`.`status` AS `status`,`v`.`forma_pago` AS `forma_pago`,`v`.`condicion_pago` AS `condicion_pago`,`v`.`condicion_embarque` AS `condicion_embarque`,`v`.`plazo_entrega` AS `plazo_entrega`,(case `v`.`status` when '1' then 'pendiente' else '' end) AS `str_status`,ifnull((select `clientes`.`nombre` from `clientes` where (`clientes`.`id_cliente` = `v`.`id_cliente`)),'') AS `cliente`,ifnull((select `clientes`.`rfc` from `clientes` where (`clientes`.`id_cliente` = `v`.`id_cliente`)),'') AS `rfc`,concat_ws(' ',ifnull((select `clientes`.`nombre` from `clientes` where (`clientes`.`id_cliente` = `v`.`id_cliente`)),''),ifnull((select `clientes`.`rfc` from `clientes` where (`clientes`.`id_cliente` = `v`.`id_cliente`)),'')) AS `campo_buscar` from `ventas` `v` where ((`v`.`tipo` = 1) and (`v`.`tipo` = 3));

--
-- Definition for view v_cotizaciones_detalle
--
CREATE OR REPLACE 
VIEW v_cotizaciones_detalle
AS
	select `vd`.`id_detalle` AS `id_detalle`,`vd`.`id_venta` AS `id_venta`,`vd`.`id_producto` AS `id_producto`,`vd`.`cantidad` AS `cantidad`,`vd`.`precio` AS `precio`,`vd`.`importe_iva` AS `importe_iva`,`vd`.`importe_ieps` AS `importe_ieps`,`vd`.`unidad` AS `unidad`,`vd`.`total` AS `total` from `ventas_detalle` `vd`;

-- 
-- Dumping data for table alm_categorias
--

-- Table gm_negocio.alm_categorias does not contain any data (it is empty)

-- 
-- Dumping data for table alm_movimientos
--

-- Table gm_negocio.alm_movimientos does not contain any data (it is empty)

-- 
-- Dumping data for table alm_proveedores
--
INSERT INTO alm_proveedores VALUES
(1, 'ANGEL GUTIERREZ MONOLA', NULL, NULL, 'GUMA91269K3', 'BOULEVARD MANUEL AVILA CAMACHO', '114', '', 'CENTRO', '96400', 'COATZALCOALCOS', 'COATZACOALCOS', 'VERACRUZ', '921232', 'gutierrez.monola@gmail.com');

-- 
-- Dumping data for table cfg_bitacora
--

-- Table gm_negocio.cfg_bitacora does not contain any data (it is empty)

-- 
-- Dumping data for table cfg_configuracion
--
INSERT INTO cfg_configuracion VALUES
(1, 'x', 'xx', 'xxx', 'xx', 'x', 'xx', 'xx', 'xxx', 'xx', 'xx', 'xx', 'x', 'x', 0.00, 0.00, 0.00, 0.00, 'MODIFICAR', 'X', 1, 0, 1, '', '', '', 'xxx', '', '', '', NULL, NULL, NULL, NULL);

-- 
-- Dumping data for table cfg_usuarios
--

-- Table gm_negocio.cfg_usuarios does not contain any data (it is empty)

-- 
-- Dumping data for table clientes
--
INSERT INTO clientes VALUES
(1, 'ANGEL GUTIERREZ MONOLA', NULL, ' ', 'GUMA91269K3', 'BOULEVARD MANUEL AVILA CAMACHO', '114', '', 'CENTRO', '96400', 'COATZALCOALCOS', 'COATZACOALCOS', 'VERACRUZ', '921232', 'gutierrez.monola@gmail.com'),
(2, 'jose alberto', '', 'jose', '123123', 'qweqw', '5', '34', 'centro', '96400', 'qwe', 'qw', 'qwe', '9211165413', 'agutierrez@quaxar.com'),
(3, 'iadkj', '', 'otro', 'asd', 'jljlkasd', 'kjl', 'lkjlk', 'lj', 'lkj', 'ljsad', 'jalksjd', 'jlkj', 'lkjlk', 'ljljk');

-- 
-- Dumping data for table cont_categorias
--
INSERT INTO cont_categorias VALUES
(3, 'adasd', '', 'asdasd'),
(6, 'Nuevo', '', 'Modificado');

-- 
-- Dumping data for table cont_cuentas
--
INSERT INTO cont_cuentas VALUES
(1, 'cuenta¿', 'askjhaskhsda'),
(2, 'asd', 'asd');

-- 
-- Dumping data for table alm_productos
--

-- Table gm_negocio.alm_productos does not contain any data (it is empty)

-- 
-- Dumping data for table compras
--

-- Table gm_negocio.compras does not contain any data (it is empty)

-- 
-- Dumping data for table cont_movimientos
--

-- Table gm_negocio.cont_movimientos does not contain any data (it is empty)

-- 
-- Dumping data for table ventas
--
INSERT INTO ventas VALUES
(1, NULL, NULL, '', '2015-12-01 22:16:07', NULL, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000, '', 0, '', '', '', '', 0, NULL, '0.00', 0),
(2, NULL, NULL, '', '2015-12-01 22:21:08', NULL, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000, '', 0, '', '', '', '', 0, NULL, '0.00', 0),
(3, NULL, NULL, '', '2015-12-01 22:29:51', NULL, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000, '', 0, '', '', '', '', 0, NULL, '0.00', 0);

-- 
-- Dumping data for table alm_movimiento_detalles
--

-- Table gm_negocio.alm_movimiento_detalles does not contain any data (it is empty)

-- 
-- Dumping data for table compras_detalle
--

-- Table gm_negocio.compras_detalle does not contain any data (it is empty)

-- 
-- Dumping data for table ventas_detalle
--

-- Table gm_negocio.ventas_detalle does not contain any data (it is empty)

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;